

service: LamdaTestAws-nodejs # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /
         method: get
imageResize:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /imageResize
         method: get

# AKIAISBYXFZ3SZBZQQOQ
# 54YJZaQrjMgRpIOppqvOxd2Tu+bBBbNpgIBt56EJ
